"""SLICE V step 5 — the evidence EMITTER.

`docs/plans/slice-v-step5-evidence.md` is generated by this script and never typed. That is
§ 5.19 (xi)'s rule, and step 5 tightens it one notch on step 4: step 4's write-up says its
evidence file was *"generated from the artifacts by a script"*, and that script is not in the
repo. This one is, so the claim is checkable rather than remembered.

It reads three things:

* the gate's own printed rows — by RUNNING `cargo test --release --test slice_v_dispatch --
  --nocapture` here, so the numbers in the doc are this tree's, not a stale log's;
* the injection table written by `inject_slice_v.py --dispatch`;
* the PREDICTIONS, which are literals below because they were pre-registered before the
  injection run and a prediction read back out of the result it is being compared with is not
  a prediction.

    .venv\\Scripts\\python.exe rust\\oracle\\emit_slice_v_step5_evidence.py
"""
import io
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RUST = os.path.join(ROOT, "rust")
TMP = r"M:\claud_projects\temp\rust-phase7"
OUT = os.path.join(ROOT, "docs", "plans", "slice-v-step5-evidence.md")

# Pre-registered at `M:\claud_projects\temp\rust-phase7\step5_predictions.txt` BEFORE the
# `--dispatch` run. Verbatim, including the one that was wrong.
PREDICTED = {
    "I1_local_armed_core": ("CAUGHT", 4),
    "I2_hp_arm_dropped": ("CAUGHT", 3),
    "I3_smooth_shape_cubed": ("CAUGHT", 2),
    "I4_erosion_inverted": ("MISSED", 0),
    "I5_incidence_lever_sign": ("MISSED", 0),
    "I6_arm_reads_the_wrong_shaft": ("CAUGHT", 2),
}

# Which gates read the committed golden at all. The distinction is the whole point of a
# MANUFACTURED gate, so it is recorded per test rather than asserted in prose.
READS_GOLDEN = {
    "the_hand_built_machine_is_the_shipped_one": False,
    "the_local_armed_core_breaks_rung_57s_own_currency": True,
    "the_six_channels_of_the_plan_reproduce_live_on_both_sides": True,
    "a_constant_setting_is_the_negative_control_and_the_wrapper_did_run": False,
    "the_scoped_port_reads_a_scheduled_machine_as_an_unstatored_one": False,
    "the_remarching_reader_is_immune_and_that_is_a_call_order_property": False,
}


def run_gate():
    log = os.path.join(TMP, "step5_evidence_gate.txt")
    with io.open(log, "w", encoding="utf-8", errors="replace") as fh:
        pr = subprocess.run(["cargo", "test", "--release", "--test", "slice_v_dispatch",
                             "--", "--nocapture"],
                            cwd=RUST, stdout=fh, stderr=subprocess.STDOUT, timeout=1800)
    text = io.open(log, encoding="utf-8", errors="replace").read()
    return pr.returncode, text


def parse_channels(text):
    """The six `§ 5.20 (ii)` rows the gate prints, straight off its stdout."""
    rows = []
    pat = re.compile(r"^(\w+)\s+(\S+)\s+([\d.e+-]+) -> ([\d.e+-]+)\s+([\d.]+) %\s+"
                     r"\(miss ([\d.e+-]+) / bar (\S+)\)")
    for line in text.splitlines():
        m = pat.match(line.strip())
        if m:
            rows.append(m.groups())
    return rows


def parse_headline(text):
    m = re.search(r"^P5: margin_min_lp (\S+) -> (\S+)\s+\(([\d.]+) %\), npts (\d+) -> (\d+)",
                  text, re.M)
    return m.groups() if m else None


def parse_control(text):
    m = re.search(r"^const_lp: (\d+) wrapped calls, (\d+) of 9 readings moved", text, re.M)
    return m.groups() if m else None


def parse_counts(text):
    m = re.search(r"test result: (\w+)\. (\d+) passed; (\d+) failed; (\d+) ignored", text)
    return m.groups() if m else None


def read_table(fname):
    p = os.path.join(TMP, fname)
    if not os.path.exists(p):
        return []
    rows = []
    with io.open(p, encoding="utf-8") as fh:
        next(fh)
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 4:
                rows.append(parts)
    return rows


def main():
    rc, text = run_gate()
    channels = parse_channels(text)
    headline = parse_headline(text)
    control = parse_control(text)
    counts = parse_counts(text)
    inj = read_table("dispatch_injection_table.txt")
    self_inj = read_table("self_injection_table.txt")

    o = []
    w = o.append
    w("# Slice V step 5 — the measured evidence")
    w("")
    w("Emitted, not typed — by `rust/oracle/emit_slice_v_step5_evidence.py`, which RUNS the gate")
    w("and parses its own stdout. The narrative and every conclusion drawn from these tables live")
    w("in `docs/plans/todo-rust-port.md` § 5.20 step 5; this file is the data behind them.")
    w("")
    w("**How to regenerate.**")
    w("")
    w("```text")
    w(r".venv\Scripts\python.exe rust\oracle\inject_slice_v.py --dispatch")
    w(r".venv\Scripts\python.exe rust\oracle\inject_slice_v.py --self")
    w(r".venv\Scripts\python.exe rust\oracle\emit_slice_v_step5_evidence.py")
    w("```")
    w("")
    w("## 1. The gate")
    w("")
    if counts:
        w("`cargo test --release --test slice_v_dispatch` — **%s, %s passed, %s failed, "
          "%s ignored** (exit %d)." % (counts[0], counts[1], counts[2], counts[3], rc))
    w("")
    if headline:
        w("**P5, the headline.** `margin_min_lp` on the `both` arming, clean against the SAME")
        w("object with the arming scoped to the close:")
        w("")
        w("```text")
        w("clean   %s   (the committed golden `A/both/tsm/margin_min_lp`)" % headline[0])
        w("scoped  %s" % headline[1])
        w("moved   %s %%          npts %s -> %s" % (headline[2], headline[3], headline[4]))
        w("```")
        w("")
    if control:
        w("**The negative control.** `const_lp`: **%s** wrapped calls, **%s of 9** readings"
          % (control[0], control[1]))
        w("moved. A constant setting is applied by the constructor and never passes through")
        w("`_arm`, so scoping `_arm` cannot reach it — § 5.20 (ii)'s exact-zero row, live.")
        w("")
    w("## 2. § 5.20 (ii)'s six channels, both columns computed live")
    w("")
    w("| arming | key | clean | scoped | moved | miss | bar | used |")
    w("|---|---|---|---|---|---|---|---|")
    for tag, key, a, b, pct, miss, bar in channels:
        try:
            used = "%.0f %%" % (100.0 * float(miss) / float(bar))
        except (ValueError, ZeroDivisionError):
            used = "?"
        w("| `%s` | `%s` | %s | %s | %s %% | %s | %s | %s |" % (tag, key, a, b, pct, miss,
                                                                bar, used))
    w("")
    w("The clean column is asserted against `oracle/slice_v_pypy.tsv` **by key**; the scoped")
    w("column against § 5.20 (ii)'s printed value at half a unit in its own last printed place.")
    w("")
    w("## 3. The six injections against the manufactured gate")
    w("")
    w("`inject_slice_v.py --dispatch` — the step-3/4 harness with a third mode. Predictions were")
    w("written before the run; both columns are here so a wrong one cannot be quietly dropped.")
    w("")
    w("**A `MISSED` row here is not a coverage failure.** I4 (`erosion`) and I5 (the incidence")
    w("lever) are not in this file's reader chain and it builds no incidence floor — the ORACLE")
    w("covers both (14 keys and a PANIC-BEFORE-COMPARE). A carrier gate that fired on everything")
    w("would not be measuring the carrier; `const_lp`'s exact zero is the same statement from the")
    w("other side.")
    w("")
    w("**`the_hand_built_machine_is_the_shipped_one` is green under every row, and that is**")
    w("**correct.** It is an equality between two objects built the same way, so a `src`-side bug")
    w("moves both sides together. Its detector is a divergence between the CONSTRUCTOR and the")
    w("hand-build — which no injection in this set manufactures.")
    w("")
    w("| injection | predicted | measured | predicted n | measured n | failing gates |")
    w("|---|---|---|---|---|---|")
    for name, status, n, gates in inj:
        pstat, pn = PREDICTED.get(name, ("?", "?"))
        mark = "" if (pstat == status and str(pn) == n) else " ⚠"
        names = ", ".join("`%s`" % g for g in gates.split(";") if g) or "—"
        w("| `%s` | %s | **%s**%s | %s | %s | %s |" % (name, pstat, status, mark, pn, n, names))
    w("")
    w("## 3b. The gate's OWN manufactured bug, mutated")
    w("")
    w("Every row above patches `rust/src/` — it asks *does the gate notice when the PORT is")
    w("wrong?* It says nothing about the mutation the gate itself carries. A wrapper that restored")
    w("only ONE of the two maps is a PARTIAL carrier bug in the INSTRUMENT, and the four")
    w("difference-asserting gates could still have passed at their pinned values. `--self` patches")
    w("the TEST FILE instead:")
    w("")
    w("| mutation of the wrapper | status | gates failing |")
    w("|---|---|---|")
    for name, status, n, gates in self_inj:
        names = ", ".join("`%s`" % g for g in gates.split(";") if g) or "—"
        w("| `%s` | **%s** | %s of 6: %s |" % (name, status, n, names))
    w("")
    w("Both fire **4 of 6** — the same four as I1, and the narrow variant (HP restore dropped in")
    w("the FUEL wrapper alone) is not confined to the HP armings, because the two spools are")
    w("coupled through the shaft state. That is step 3's I2 finding recurring on the instrument")
    w("rather than on the port.")
    w("")
    w("## 4. Which gates need the golden, and which do not")
    w("")
    w("A manufactured gate earns its place only where it says something a golden comparison")
    w("cannot. Recorded per test rather than claimed in prose:")
    w("")
    w("| `#[test]` | reads `slice_v_pypy.tsv` |")
    w("|---|---|")
    for k in sorted(READS_GOLDEN):
        w("| `%s` | %s |" % (k, "yes" if READS_GOLDEN[k] else "**no**"))
    w("")
    w("The four that read nothing on disk are the ones that survive a regenerated golden.")

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(o) + "\n")
    print("wrote %s (%d channel rows, %d injections, %d self-injections)"
          % (OUT, len(channels), len(inj), len(self_inj)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
