r"""GOLDEN NUMERIC FINGERPRINT — the absolute-value gate this project did not have.

Every other tight assertion in this suite (185 of them at <=1e-9) is a SAME-RUN RELATIVE
IDENTITY: it computes two quantities in one process and asserts they agree. That is the right
shape for a reduce-to-prior contract, and it is the project's spine. But it has a blind spot
that no amount of it can close: **if BOTH sides move together, every one of them stays green.**

Nothing in this repo pinned an absolute number. So an unintended numerical change to the model —
from a refactor, a library update, a solver rewrite, an interpreter swap — was undetectable. This
is not hypothetical: the rung-30 `_sonic_throat` closed-form fix moved every CPG result by 1-2 ulp
and the suite could not have told you. That was benign; the next one might not be.

This module pins ABSOLUTE values, measured once on CPython, committed to
`tests/golden/numeric_fingerprint.json`, and compared with a disclosed per-kernel tolerance.

--------------------------------------------------------------------------------------------
THE GOLDENS ARE CPYTHON'S, AND THEY STAY CPYTHON'S
--------------------------------------------------------------------------------------------
The committed file was generated by the interpreter recorded in its own `meta` block
(CPython 3.14.3, at the repo state noted there). If this project later switches to PyPy
(`docs/plans/todo-pypy-switch.md`), **the goldens must NOT be regenerated as part of that
switch.** Regenerating them under the new interpreter destroys the only cross-interpreter
anchor that exists and reduces this file to "PyPy agrees with itself" — which is precisely the
hole it was written to close.

Consequence, stated plainly: the per-kernel tolerances below are LOAD-BEARING PERMANENTLY, not
just during a transition. They are the width of the band inside which two interpreters' libm
implementations are allowed to disagree without this project calling it a regression.

--------------------------------------------------------------------------------------------
TOLERANCES — where the numbers come from
--------------------------------------------------------------------------------------------
Measured 2026-07-31, CPython 3.14.3 vs PyPy 3.11.15 (7.3.23), 133 equilibrium-side values +
96 CPG ladder values + the rung-66 trajectory (341 rows x 18 keys = 6 138 floats) and its 12
discrete readings. Evidence: `docs/plans/todo-pypy-switch.md` § 0.

Verified against those goldens by running this module under PyPy: **every arm green, and no arm
consumes more than 10.5% of its tolerance (none less than 2.4%)** — snug without being on the
edge. The two exact arms differed in 0 of 96 and 0 of 6 152 values.

The rule is ONE ROUND DECADE ABOVE THE MEASURED DRIFT — tight enough to catch a real regression,
loose enough not to flake on known interpreter noise. Each tolerance below records the drift it
was calibrated against, so the constant is disclosed rather than magic.

The two CPG arms are the exception: they were measured EXACT (zero differing values out of
96 + 6 152), so they assert bit-equality. That is a deliberate, and slightly risky, choice — see
`docs/plans/todo-pypy-switch.md` R2. If it ever proves fragile, demote THOSE arms to a tolerance
and say so; do not quietly loosen the rest.

Calibration caveat: each tolerance rests on ONE sample point per kernel. If a future slice
broadens the sample and a drift exceeds its tolerance, that is a disclosed edit recording the
new measured number — not a quiet bump.

--------------------------------------------------------------------------------------------
SENSITIVITY — MEASURED, not asserted
--------------------------------------------------------------------------------------------
A tolerance says what this gate will TOLERATE. It does not say what the gate will CATCH: a
kernel's own arithmetic can amplify a small input change into a large output one, or bury it.
So this was measured rather than reasoned about — perturb each kernel's primary physical input
by a relative epsilon, sweep, and record the smallest decade that turns the arm red
(`M:\claud_projects\temp\pypy-fingerprint\sensitivity.py`, 2026-07-31):

    kernel    tol      smallest relative input change DETECTED
    cpg       exact    1e-14
    r66       exact    1e-14
    A         1e-10    1e-10
    B         1e-11    1e-11
    C         1e-13    1e-12
    D         1e-7     1e-13   <- the turbine bisection AMPLIFIES ~6 decades past its tolerance
    E         1e-9     1e-9
    F         1e-4     1e-5    <- THE WEAKEST ARM. Disclosed, not hidden.

**The honest headline: this gate catches a relative change of 1e-5 anywhere, and 1e-10 or
tighter on seven of its eight arms.** Kernel F is the floor and cannot be improved by tightening
its tolerance — 3.7e-6 of genuine cross-interpreter drift lives underneath it, so a tighter
constant would buy flakiness rather than sensitivity. If rung 26's freeze-out numbers ever need
guarding below 1e-5, the fix is a better-conditioned probe (its worst values are
differences-of-near-equals), not a smaller number here.

--------------------------------------------------------------------------------------------
IF THIS TEST FAILS — the procedure
--------------------------------------------------------------------------------------------
The failure message names the first differing keys with golden-vs-actual and the relative
error. Do NOT reach for regeneration. Work the decision:

  1. Is it a SHAPE failure ("the kernel's API changed")? Then a signature moved, not the
     arithmetic. Fix the probe here to match the new API and regenerate only that kernel's
     names — the values must be unchanged.
  2. Is it a REGRESSION? A number the model is supposed to produce changed because something
     broke. Fix the code. This is what the gate is for.
  3. Is it an ACCEPTED numerical shift? A deliberate change (a better solver, a closed form
     replacing a bisection) legitimately moves last bits. The worked precedent is the rung-30
     fix, which moved every CPG value by 1-2 ulp for a good reason. Then and only then:
     regenerate, READ THE PRINTED DIFF, and record in the commit message WHICH values moved,
     BY HOW MUCH, and WHY that was correct.

Regenerate with:  python tests/test_numeric_fingerprint.py --regenerate
It prints every changing value before writing. If that diff is longer than you expected, stop.

--------------------------------------------------------------------------------------------
Kernels
--------------------------------------------------------------------------------------------
  cpg  the CPG structural ladder — design run + a 6-point off-design throttle sweep. This is
       the path rungs 31-66 (every transient, ~72% of gate minutes) actually run.
  r66  the rung-66 two-lag cascade march, BOTH clocks armed: 341 rows x 18 keys of trajectory
       PLUS the 12 DISCRETE readings (argmin/argmax/limiter edge rows). The discrete ones are the
       real prize — a last-bit perturbation flipping a min-select crossing is the failure mode
       that a purely continuous comparison can miss entirely, and it is what rungs 46-66 measure.
  A    equilibrium design point       -> gas.py _equil_solve Newton + _gauss_solve
  B    mixing-PDF geometry            -> gas.py _spatial_local_field (rungs 22/24 integrals)
  C    zoned NOx chemistry            -> Arrhenius exp/log + the quench march
  D    shifting turbine               -> _work_limited_expand bisection, pr_t / powers / tau**0.5
  E    off-design matcher, EQUILIBRIUM gas -> _solve_choked_turbine bisection + choked_mfp
  F    freeze-out nozzle march        -> rung-26 local Da(T,p) clock

A-F are the transcendental/equilibrium side: `expm1`, `log1p`, `erf` and naive `sum()`
reassociation, which is exactly where the two interpreters disagree and where the CPG closed
forms do not go.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from turbojet.gas import Gas, JetMixing, FreezeOut, _spatial_local_field  # noqa: E402
from turbojet.engine import (  # noqa: E402
    FlightCondition, build_turbojet, build_two_spool_turbojet, OffDesignMatcher, ComponentMap,
    TwoLagCascadeTransient, BleedLimiter, SurgeLimiter, AsymmetricLag,
)

_HERE = os.path.dirname(os.path.abspath(__file__))
GOLDEN_PATH = os.path.join(_HERE, "golden", "numeric_fingerprint.json")

# --------------------------------------------------------------------------- tolerances
# tol = one round decade above the measured CPython-vs-PyPy drift (see the module docstring).
# 0.0 means BIT-EQUALITY is asserted, because zero values differed across interpreters.
TOL = {
    "cpg": 0.0,      # measured EXACT — 0 of 96 values differed
    "r66": 0.0,      # measured EXACT — 0 of 6 152 (6 140 floats + 12 discrete readings) differed
    "A":   1e-10,    # measured drift 6.6e-12
    "B":   1e-11,    # measured drift 1.0e-12
    "C":   1e-13,    # measured drift 2.4e-15
    "D":   1e-7,     # measured drift 1.0e-8
    "E":   1e-9,     # measured drift 6.6e-11
    "F":   1e-4,     # measured drift 3.7e-6  <- the WEAKEST arm; see test_sensitivity_is_measured
}

# --------------------------------------------------------------------------- shared conditions
FLIGHT = FlightCondition(T0=250.0, p0=50_000.0, M0=0.85)
PI_C, TT4 = 10.0, 1500.0
LOSSES = dict(pi_d=0.97, eta_c=0.88, eta_b=0.99, pi_b=0.96, eta_t=0.90, eta_m=0.99, pi_n=0.98)


def _cpg_gas():
    """The self-consistent CPG dual gas rungs 31-66 use: R_t = (g-1)/g*cp_t exactly."""
    g, cp = 1.3, 1239.0
    return Gas(gamma_c=1.4, cp_c=1004.0, R_c=286.9,
               gamma_t=g, cp_t=cp, R_t=(g - 1.0) / g * cp, hPR=42.8e6)


def _floats_of(obj, prefix, out):
    """Every public float attribute of a result object, sorted for determinism."""
    for attr in sorted(a for a in dir(obj) if not a.startswith("_")):
        v = getattr(obj, attr)
        if isinstance(v, float):
            out[f"{prefix}.{attr}"] = v


# --------------------------------------------------------------------------- kernels
# Each returns {name: value}. Values are float (compared at the kernel's tolerance) or
# int/list (compared EXACTLY — these are the discrete readings, where "close" is meaningless).

def kernel_cpg():
    """The CPG structural ladder: design run + the rung-31 off-design throttle sweep."""
    out = {}
    design = build_turbojet(_cpg_gas(), PI_C, TT4, FLIGHT.p0, nozzle_convergent=True, **LOSSES)
    r = design.run(FLIGHT, 1.0)
    for k in sorted(r.stations):
        out[f"design.st{k}.Tt"] = r.stations[k].Tt
        out[f"design.st{k}.pt"] = r.stations[k].pt
    m = OffDesignMatcher(design, FLIGHT, 1.0)
    for Tt4 in (1500.0, 1400.0, 1300.0, 1200.0, 1100.0, 1000.0):
        _floats_of(m.match(FLIGHT, Tt4), f"od{int(Tt4)}", out)
    return out


def kernel_r66():
    """The rung-66 two-lag cascade march, both clocks armed — trajectory AND discrete events."""
    PI_LPC, PI_HPC = 3.0, 6.0
    REAL = dict(pi_d=0.97, eta_lpc=0.90, eta_hpc=0.88, eta_b=0.99, pi_b=0.96,
                eta_hpt=0.92, eta_lpt=0.90, eta_m=0.99, pi_n=0.98)
    FLOOR, PHI, B = 0.55, 0.80, 0.10
    LO, HI, DS, SETTLE, R = 1000.0, 1400.0, 0.005, 1.2, 0.5
    lp = ComponentMap(a=0.20, b=0.05, sigma=0.1, l=0.7).with_phi_surge(FLOOR)
    hp = ComponentMap(a=0.08, b=0.15, sigma=0.1, l=1.0).with_phi_surge(FLOOR)
    design = build_two_spool_turbojet(_cpg_gas(), PI_LPC, PI_HPC, TT4, FLIGHT.p0,
                                      nozzle_convergent=True, **REAL)
    m = TwoLagCascadeTransient(design, FLIGHT, 1.0, map_lp=lp, map_hp=hp, rho=1.0,
                               bleed_lim=BleedLimiter(phi_lim=PHI, b_max=B, tau=0.05))
    traj = m._stator_march(FLIGHT, LO, HI, R, SETTLE, DS,
                           surge=SurgeLimiter.from_margin(lp, "lp", PHI / FLOOR - 1.0),
                           lag=AsymmetricLag(tau_att=0.05, tau_rel=0.15))[0]

    out = {"rows": len(traj)}
    keys = [k for k in sorted(traj[0]) if isinstance(traj[0][k], float)]
    out["keys"] = keys                                   # pinned: a moved key is a SHAPE change
    for i, p in enumerate(traj):
        for k in keys:
            out[f"t[{i}].{k}"] = p[k]
    # The DISCRETE readings — where a last-bit shift would show up as a JUMP, not a drift.
    for k in ("phi_lp", "phi_hp"):
        if k in keys:
            j = min(range(len(traj)), key=lambda i: traj[i][k])
            out[f"argmin.{k}"] = j
            out[f"min.{k}"] = traj[j][k]
    for k in ("g", "b", "mf", "Tt4"):
        if k in keys:
            out[f"edges.{k}"] = [i for i in range(1, len(traj))
                                 if (traj[i][k] > 0.0) != (traj[i - 1][k] > 0.0)]
            out[f"argmax.{k}"] = max(range(len(traj)), key=lambda i: traj[i][k])
    return out


def _equilibrium_design():
    """The shared equilibrium design run behind kernels A / C / D / E / F."""
    gas = Gas.reacting_equilibrium()
    res = build_turbojet(gas, PI_C, TT4, FLIGHT.p0, **LOSSES).run(FLIGHT, 50.0)
    return gas, res


def kernel_A():
    """Equilibrium design point — the _equil_solve Newton and its _gauss_solve linear algebra."""
    gas, res = _equilibrium_design()
    out = {}
    for k in sorted(res.stations):
        st = res.stations[k]
        out[f"st{k}.Tt"], out[f"st{k}.pt"], out[f"st{k}.far"] = st.Tt, st.pt, st.far
    for attr in ("thrust", "tsfc", "f", "eta_th", "eta_p", "eta_o", "v9"):
        if hasattr(res, attr):
            out[attr] = getattr(res, attr)
    return out


def kernel_B():
    """Mixing-PDF geometry — the rung-22/24 cross-plane integrals (erf, log1p, naive sums)."""
    mix = JetMixing(J=16.0, C_e=0.20, U_c=75.0, shape_n=2.0)
    g_field, tau_of_xi, F = _spatial_local_field(0.02718, 1.5, 0.0625, 0.10, 16.0, mix.tau_q,
                                                 ny=32, nz=32)
    out = {"g_spatial": g_field, "F_shape": F, "tau_q": mix.tau_q}
    for k in range(21):                                  # tau(xi) sampled across the whole bell
        out[f"tau_of_xi[{k}]"] = float(tau_of_xi(0.001 + k * (0.070 - 0.001) / 20.0))
    for JJ in (4.0, 9.0, 36.0, 64.0):                    # F over J: the U-shape the rung reads
        gj, _, Fj = _spatial_local_field(0.02718, 1.5, 0.0625, 0.10, JJ,
                                         JetMixing(J=JJ, C_e=0.20, U_c=75.0, shape_n=2.0).tau_q,
                                         ny=32, nz=32)
        out[f"J{int(JJ)}.g"], out[f"J{int(JJ)}.F"] = gj, Fj
    return out


def kernel_C():
    """Zoned NOx chemistry — Arrhenius exp/log through the quench march."""
    gas, res = _equilibrium_design()
    st3, st4 = res.stations["3"], res.stations["4"]
    z = gas.zoned_nox(st4.far, st3.Tt, st4.Tt, st4.pt, tau=3e-3, phi_primary=1.5,
                      mixing=JetMixing(J=16.0, C_e=0.20, U_c=75.0, shape_n=2.0),
                      quench_ngrid=12, quench_nsteps=40)
    out = {}
    _floats_of(z, "z", out)
    return out


def kernel_D():
    """Shifting turbine — the _work_limited_expand bisection (pr_t, powers, tau**0.5)."""
    gas, res = _equilibrium_design()
    st4 = res.stations["4"]
    delta_h = gas.h_t(st4.Tt, st4.far) - gas.h_t(res.stations["5"].Tt, st4.far)
    out = {}
    _floats_of(gas.shifting_turbine(st4.far, st4.Tt, st4.pt, delta_h), "sh", out)
    return out


def kernel_E():
    """Off-design matcher ON THE EQUILIBRIUM GAS — the same solver as `cpg`, different gas."""
    gas = Gas.reacting_equilibrium()
    design = build_turbojet(gas, PI_C, TT4, FLIGHT.p0, nozzle_convergent=True, **LOSSES)
    m = OffDesignMatcher(design, FLIGHT, 1.0)
    out = {}
    for Tt4 in (1500.0, 1300.0, 1100.0):
        _floats_of(m.match(FLIGHT, Tt4), f"{int(Tt4)}", out)
    return out


def kernel_F():
    """Freeze-out nozzle march — rung 26's local Da(T,p) clock. The widest-drift kernel."""
    gas, res = _equilibrium_design()
    st4, st5 = res.stations["4"], res.stations["5"]
    fo = gas.freeze_out_nozzle(st4.far, st4.Tt, st4.pt, st5.Tt, st5.pt, FLIGHT.p0,
                               freeze_out=FreezeOut(L=0.3))
    out = {}
    _floats_of(fo, "fo", out)
    return out


KERNELS = {"cpg": kernel_cpg, "r66": kernel_r66, "A": kernel_A, "B": kernel_B,
           "C": kernel_C, "D": kernel_D, "E": kernel_E, "F": kernel_F}


# --------------------------------------------------------------------------- encode / compare
# Floats round-trip through .hex() EXACTLY; repr() at 17 digits also round-trips but hex makes a
# last-bit change visible to the eye in the committed diff, which repr does not.
def _encode(v):
    return {"f": v.hex()} if isinstance(v, float) else v


def _decode(v):
    return float.fromhex(v["f"]) if isinstance(v, dict) and "f" in v else v


def _close(a, b, tol):
    """`a` measured, `b` golden. tol == 0.0 means bit-equality."""
    if a == b:
        return True, 0.0
    if not isinstance(a, float) or not isinstance(b, float):
        return False, float("inf")
    err = abs(a - b) / abs(b) if b != 0.0 else abs(a)
    return (err <= tol) if tol > 0.0 else False, err


def _show(v):
    return f"{v!r}  [{v.hex()}]" if isinstance(v, float) else repr(v)


def _load_golden():
    with open(GOLDEN_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def _check(name):
    """Shape first, then values — a signature drift must not read as a numeric regression."""
    golden = _load_golden()
    assert name in golden["kernels"], (
        f"kernel {name!r} has no golden. Regenerate deliberately — see the module docstring.")
    want = {k: _decode(v) for k, v in golden["kernels"][name].items()}
    got = KERNELS[name]()

    missing, extra = sorted(set(want) - set(got)), sorted(set(got) - set(want))
    assert not missing and not extra, (
        f"kernel {name!r}: THE KERNEL'S API CHANGED, NOT ITS ARITHMETIC — this is a signature "
        f"drift, not a numeric regression.\n"
        f"  in the golden but no longer produced ({len(missing)}): {missing[:8]}\n"
        f"  newly produced, not in the golden ({len(extra)}): {extra[:8]}\n"
        f"Fix the probe to match the new API; the VALUES must be unchanged.")

    tol = TOL[name]
    bad = []
    for k in sorted(want):
        ok, err = _close(got[k], want[k], tol)
        if not ok:
            bad.append((k, want[k], got[k], err))
    assert not bad, (
        f"kernel {name!r}: {len(bad)} of {len(want)} values moved beyond tol={tol:g}"
        + (" (BIT-EQUALITY asserted — this kernel is measured exact)" if tol == 0.0 else "")
        + "\n" + "\n".join(
            # hex alongside repr: on the bit-exact arms the interesting failure is a 1-ulp shift,
            # and "...ff4p+9 vs ...ff5p+9" says that at a glance where two 17-digit reprs do not.
            f"  {k}\n    golden {_show(w)}\n    actual {_show(g)}\n    rel err {e:.3e}"
            for k, w, g, e in bad[:5])
        + (f"\n  ... and {len(bad) - 5} more" if len(bad) > 5 else "")
        + "\nDo NOT regenerate reflexively — work the procedure in this module's docstring.")


# --------------------------------------------------------------------------- the gates
# Named `test_golden_fingerprint_*` so conftest._is_spine keeps them out of slow-tagging: they
# are absolute-value gates and must run on EVERY invocation, not only under --runslow. The two
# meta-guards below deliberately do NOT carry that prefix — they are sub-millisecond, so no
# threshold can ever reach them, and the spine override should stay as narrow as its reason.

def test_golden_fingerprint_cpg():
    """The CPG structural ladder — rungs 31-66's actual path. Bit-equality."""
    _check("cpg")


def test_golden_fingerprint_r66():
    """The rung-66 cascade: 6 152 trajectory floats + every discrete event. Bit-equality."""
    _check("r66")


def test_golden_fingerprint_A_equilibrium_cycle():
    _check("A")


def test_golden_fingerprint_B_mixing_pdf():
    _check("B")


def test_golden_fingerprint_C_zoned_nox():
    _check("C")


def test_golden_fingerprint_D_shifting_turbine():
    _check("D")


def test_golden_fingerprint_E_offdesign_equilibrium():
    _check("E")


def test_golden_fingerprint_F_freeze_out():
    _check("F")


def test_golden_file_declares_its_provenance():
    """The goldens' whole value is being CPython's. If the meta block ever stops saying so —
    because someone regenerated under another interpreter — the anchor is gone and this file
    silently degrades into 'the current interpreter agrees with itself'. Guard it."""
    meta = _load_golden()["meta"]
    assert meta["implementation"] == "cpython", (
        f"the golden file was generated by {meta['implementation']!r}, not CPython. "
        "Its entire value is being an INDEPENDENT anchor — see the module docstring. "
        "Restore the CPython-generated file from git; do not accept this.")
    for k in ("version", "generated", "repo_sha"):
        assert meta.get(k), f"golden meta is missing {k!r} — provenance must be complete"


def test_every_kernel_has_a_disclosed_tolerance():
    """No kernel may be compared at a tolerance that is not written down beside its measurement."""
    golden = _load_golden()
    assert set(KERNELS) == set(TOL) == set(golden["kernels"]), (
        f"kernels {sorted(KERNELS)}, tolerances {sorted(TOL)}, "
        f"goldens {sorted(golden['kernels'])} — these three sets must agree exactly")


# --------------------------------------------------------------------------- regeneration
def _regenerate():
    """Print every changing value, THEN write. The printed diff is the point of the flag."""
    import subprocess
    import time

    try:
        old = _load_golden()["kernels"]
    except (OSError, ValueError):
        old = {}
    new = {}
    for name, fn in KERNELS.items():
        print(f"  running kernel {name} ...", flush=True)
        new[name] = {k: _encode(v) for k, v in fn().items()}

    changed = 0
    for name in sorted(new):
        prev, cur = old.get(name, {}), new[name]
        for k in sorted(set(prev) | set(cur)):
            a, b = _decode(prev.get(k)) if k in prev else None, _decode(cur[k]) if k in cur else None
            if a != b:
                changed += 1
                if changed <= 40:
                    print(f"    {name}.{k}\n      was {a!r}\n      now {b!r}")
    print(f"\n  {changed} value(s) changed" + (" (first 40 shown)" if changed > 40 else ""))
    if changed:
        print("  >>> READ THAT DIFF. If it is longer than you expected, STOP and work the")
        print("  >>> procedure in this module's docstring. Record in the commit message WHICH")
        print("  >>> values moved, BY HOW MUCH, and WHY that is correct.")

    sha = ""
    try:
        sha = subprocess.run(["git", "-C", os.path.dirname(_HERE), "rev-parse", "HEAD"],
                             capture_output=True, text=True, timeout=30).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass
    doc = {"meta": {"implementation": sys.implementation.name,
                    "version": sys.version.split()[0],
                    "generated": time.strftime("%Y-%m-%d"),
                    "repo_sha": sha,
                    "note": "CPython-generated ANCHOR. Do NOT regenerate under another "
                            "interpreter — see tests/test_numeric_fingerprint.py."},
           "kernels": new}
    os.makedirs(os.path.dirname(GOLDEN_PATH), exist_ok=True)
    with open(GOLDEN_PATH, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=1, sort_keys=True)
        fh.write("\n")
    print(f"  wrote {GOLDEN_PATH} "
          f"({sum(len(v) for v in new.values())} values, {os.path.getsize(GOLDEN_PATH):,} bytes)")


if __name__ == "__main__":
    if "--regenerate" in sys.argv:
        print("REGENERATING the golden fingerprint. This destroys the previous anchor.")
        _regenerate()
    else:
        for fn_name in sorted(n for n in dir() if n.startswith("test_")):
            globals()[fn_name]()
            print("ok:", fn_name)
        print("golden fingerprint: all gates pass")
