r"""GOLDEN NUMERIC FINGERPRINT — the absolute-value gate this project did not have.

Every other tight assertion in this suite (185 of them at <=1e-9) is a SAME-RUN RELATIVE
IDENTITY: it computes two quantities in one process and asserts they agree. That is the right
shape for a reduce-to-prior contract, and it is the project's spine. But it has a blind spot
that no amount of it can close: **if BOTH sides move together, every one of them stays green.**

Nothing in this repo pinned an absolute number. So an unintended numerical change to the model —
from a refactor, a library update, a solver rewrite, an interpreter swap — was undetectable. This
is not hypothetical: the rung-30 `_sonic_throat` closed-form fix moved every CPG result by 1-2 ulp
and the suite could not have told you. That was benign; the next one might not be.

This module pins ABSOLUTE values, measured once on CPython, committed to
`tests/golden/numeric_fingerprint.json`, and compared with a disclosed per-kernel tolerance.

--------------------------------------------------------------------------------------------
THE GOLDENS ARE CPYTHON'S, AND THEY STAY CPYTHON'S
--------------------------------------------------------------------------------------------
The committed file was generated by the interpreter recorded in its own `meta` block
(CPython 3.14.3, at the repo state noted there). If this project later switches to PyPy
(`docs/plans/todo-pypy-switch.md`), **the goldens must NOT be regenerated as part of that
switch.** Regenerating them under the new interpreter destroys the only cross-interpreter
anchor that exists and reduces this file to "PyPy agrees with itself" — which is precisely the
hole it was written to close.

Consequence, stated plainly: the per-kernel tolerances below are LOAD-BEARING PERMANENTLY, not
just during a transition. They are the width of the band inside which two interpreters' libm
implementations are allowed to disagree without this project calling it a regression.

--------------------------------------------------------------------------------------------
TOLERANCES — where the numbers come from
--------------------------------------------------------------------------------------------
Measured 2026-07-31, CPython 3.14.3 vs PyPy 3.11.15 (7.3.23), 133 equilibrium-side values +
96 CPG ladder values + the rung-66 trajectory (341 rows x 18 keys = 6 138 floats) and its 12
discrete readings. Evidence: `docs/plans/todo-pypy-switch.md` § 0.

Verified against those goldens by running this module under PyPy: **every arm green, and no arm
consumes more than 10.5% of its tolerance (none less than 2.4%)** — snug without being on the
edge. The two exact arms differed in 0 of 96 and 0 of 6 152 values.

The rule is ONE ROUND DECADE ABOVE THE MEASURED DRIFT — tight enough to catch a real regression,
loose enough not to flake on known interpreter noise. Each tolerance below records the drift it
was calibrated against, so the constant is disclosed rather than magic.

The two CPG arms are the exception: they were measured EXACT (zero differing values out of
96 + 6 152), so they assert bit-equality. That is a deliberate, and slightly risky, choice — see
`docs/plans/todo-pypy-switch.md` R2. If it ever proves fragile, demote THOSE arms to a tolerance
and say so; do not quietly loosen the rest.

Calibration caveat: each tolerance rests on ONE sample point per kernel. If a future slice
broadens the sample and a drift exceeds its tolerance, that is a disclosed edit recording the
new measured number — not a quiet bump.

--------------------------------------------------------------------------------------------
SENSITIVITY — MEASURED, not asserted
--------------------------------------------------------------------------------------------
A tolerance says what this gate will TOLERATE. It does not say what the gate will CATCH: a
kernel's own arithmetic can amplify a small input change into a large output one, or bury it.
So this was measured rather than reasoned about — perturb each kernel's primary physical input
by a relative epsilon, sweep, and record the smallest decade that turns the arm red
(`M:\claud_projects\temp\pypy-fingerprint\sensitivity.py`, 2026-07-31):

    kernel    tol      smallest relative input change DETECTED
    cpg       exact    1e-14
    r66       exact    1e-14
    A         1e-10    1e-10
    B         1e-11    1e-11
    C         1e-13    1e-12
    D         1e-7     1e-13   <- the turbine bisection AMPLIFIES ~6 decades past its tolerance
    E         1e-9     1e-9
    F         1e-4     1e-5    <- THE WEAKEST ARM. Disclosed, not hidden.

**The honest headline: this gate catches a relative change of 1e-5 anywhere, and 1e-10 or
tighter on seven of its eight arms.** Kernel F is the floor and cannot be improved by tightening
its tolerance — 3.7e-6 of genuine cross-interpreter drift lives underneath it, so a tighter
constant would buy flakiness rather than sensitivity. If rung 26's freeze-out numbers ever need
guarding below 1e-5, the fix is a better-conditioned probe (its worst values are
differences-of-near-equals), not a smaller number here.

(That table is SLICE 1's eight arms. Slice 2 added eighteen more — see § SLICE 2 below, which
re-measures the floor and leaves it at 1e-5.)

--------------------------------------------------------------------------------------------
IF THIS TEST FAILS — the procedure
--------------------------------------------------------------------------------------------
The failure message names the first differing keys with golden-vs-actual and the relative
error. Do NOT reach for regeneration. Work the decision:

  1. Is it a SHAPE failure ("the kernel's API changed")? Then a signature moved, not the
     arithmetic. Fix the probe here to match the new API and regenerate only that kernel's
     names — the values must be unchanged.
  2. Is it a REGRESSION? A number the model is supposed to produce changed because something
     broke. Fix the code. This is what the gate is for.
  ** `test_golden_file_declares_its_provenance` does NOT police this decision. ** It reads the
  `meta` block, so it catches regeneration under a DIFFERENT interpreter (which writes e.g.
  "pypy" and fires). It cannot catch regeneration under CPython — the likelier accident by far,
  and the one this procedure exists to prevent. That case is procedure-only. Do not read a green
  provenance guard as permission.

  3. Is it an ACCEPTED numerical shift? A deliberate change (a better solver, a closed form
     replacing a bisection) legitimately moves last bits. The worked precedent is the rung-30
     fix, which moved every CPG value by 1-2 ulp for a good reason. Then and only then:
     regenerate, READ THE PRINTED DIFF, and record in the commit message WHICH values moved,
     BY HOW MUCH, and WHY that was correct.

Regenerate with:  python tests/test_numeric_fingerprint.py --regenerate
It prints every changing value before writing. If that diff is longer than you expected, stop.

--------------------------------------------------------------------------------------------
Kernels
--------------------------------------------------------------------------------------------
  cpg  the CPG structural ladder — design run + a 6-point off-design throttle sweep. This is
       the path rungs 31-66 (every transient, ~72% of gate minutes) actually run.
  r66  the rung-66 two-lag cascade march, BOTH clocks armed: 341 rows x 18 keys of trajectory
       PLUS the 12 DISCRETE readings (argmin/argmax/limiter edge rows). The discrete ones are the
       real prize — a last-bit perturbation flipping a min-select crossing is the failure mode
       that a purely continuous comparison can miss entirely, and it is what rungs 46-66 measure.
  A    equilibrium design point       -> gas.py _equil_solve Newton + _gauss_solve
  B    mixing-PDF geometry            -> gas.py _spatial_local_field (rungs 22/24 integrals)
  C    zoned NOx chemistry            -> Arrhenius exp/log + the quench march
  D    shifting turbine               -> _work_limited_expand bisection, pr_t / powers / tau**0.5
  E    off-design matcher, EQUILIBRIUM gas -> _solve_choked_turbine bisection + choked_mfp
  F    freeze-out nozzle march        -> rung-26 local Da(T,p) clock

A-F are the transcendental/equilibrium side: `expm1`, `log1p`, `erf` and naive `sum()`
reassociation, which is exactly where the two interpreters disagree and where the CPG closed
forms do not go.

--------------------------------------------------------------------------------------------
SLICE 2 — the rungs 3-30 DIAGNOSTIC ladder (added 2026-07-31)
--------------------------------------------------------------------------------------------
Slice 1 (above) sampled SIX equilibrium-side kernels. Slice 2 fills the machine: 18 more arms,
keyed BY RUNG so a failure names the rung that moved.

  prop  RUNGS 3/4/5/6 — the GAS PROPERTY LAYER under every factory (thermally_perfect /
        reacting / reacting_forkb / reacting_equilibrium): cp, h, pr, gamma, their INVERSES,
        Fork B's absolute-enthalpy interface, and the rung-6 Kp composition solve. This arm is
        here for SEPARABILITY, not coverage: it is the substrate every other arm stands on, so
        `prop` red means the PRIMITIVE layer moved, while a diagnostic red with `prop` green
        means that diagnostic moved. It also carries the arm's widest drift (8.9e-12, on the
        `T_from_pr_t` inverse — an iterative solve amplifying a 1-ulp property difference).
  r7    thermal_nox, plain + the rung-19 super-eq-O lift + prompt NO
  r8    zoned_nox MIXED-OUT across rung 9's phi bell (0.8 ... 2.0)
  r10   the finite-rate quench (tau_q)          r11  JetMixing (tau_q DERIVED from J)
  r12   Unmixedness                             r13  MixingPDF
  r14   nozzle_flow (the rung-14 bracket)       r15  QuenchPDF
  r16   PocketQuenchPDF (+ the 20/21 lift)      r17  exhaust_no_clamp
  r18   TransportedPDF                          r22  SpatialPDF
  r23   SpatialDwellPDF                         r24  SpatialLocalPDF
  r25   finite_rate_nozzle    r27  no_freeze_out_nozzle    r28  coupled_no_freeze_out_nozzle

RESOLUTION — the one real concession, stated up front. These arms run at REDUCED quadrature
(the `_NG/_NS/_NB/_NQ/_NXY/_NT` block below), keeping the anchor CONFIGURATION (S=0.0625, the
J values, phi_p=1.5, the design point) and cutting only node counts. ** A GREEN ARM HERE DOES
NOT GUARD THE SPEC'S QUOTED DIGIT. ** It guards the kernel's arithmetic at this resolution.

That concession was CHECKED rather than assumed, because the § 0 mechanism behind the
equilibrium-side drift is naive `sum()` reassociation, whose error grows with TERM COUNT — so a
reduced probe could systematically under-report. Re-measured at 4x the terms (2x n_bell, 2x
n_quad, 4x cross-plane cells), the drift does NOT grow:

    arm    reduced     4x terms
    r13    1.85e-15    1.85e-15
    r18    1.31e-15    1.31e-15
    r22    1.34e-15    1.31e-15
    r24    3.26e-14    2.49e-14   <- FALLS

So on these kernels the drift is not set by the quadrature sums at all; it is inherited from
the fixed upstream layer (the equilibrium design point and the Kp solve) and the quadrature
AVERAGES it down. That inherited floor is not an inference — it is the `prop` arm, measured
directly at 8.91e-12, and `prop` is upstream of every other arm in this module. The reduced
tolerances are therefore not optimistic — if anything the full-resolution paths the specs quote
are tighter.

DRIFT AND SENSITIVITY. Every slice-2 tolerance is the same one-round-decade rule, measured over
1 661 values; each consumes 1.3-9.6% of its band, the same snug-not-flaky range slice 1 landed
in. The sensitivity sweep was run only on the arms whose tolerance is >= 1e-7
(`sensitivity2.py`), because slice 1's own table showed tight arms simply detect AT their
tolerance (A 1e-10 -> 1e-10, B 1e-11 -> 1e-11, E 1e-9 -> 1e-9) while the informative cases were
the LOOSE ones (D amplifying, F weak):

    arm    tol      smallest relative input change DETECTED
    r25    1e-4     1e-5      <- ties kernel F as the gate's weakest
    r28    1e-5     1e-6

Both are loose for kernel F's exact reason: their worst values (`dS_finite`, `channel_ratio`)
are an entropy difference-of-near-equals and a log-ratio, which amplify the underlying drift.
** The gate's floor is therefore UNCHANGED at 1e-5 — now reached by two arms (F, r25) instead
of one — with everything else at 1e-6 or tighter. ** The other SIXTEEN slice-2 arms were NOT
swept; that is a recorded skip, not implied coverage, and it is safe only in the direction
claimed: a 1e-13-band arm cannot have a floor WORSE than the 1e-5 headline, but nothing here
says how much better it is.
"""
import json
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from turbojet.gas import (  # noqa: E402
    Gas, JetMixing, FreezeOut, _spatial_local_field,
    Unmixedness, MixingPDF, QuenchPDF, PocketQuenchPDF, TransportedPDF,
    SpatialPDF, SpatialDwellPDF, SpatialLocalPDF, FiniteRate, NOFreezeOut, CoupledNOFreezeOut,
    PromptNO,
)
from turbojet.engine import (  # noqa: E402
    FlightCondition, build_turbojet, build_two_spool_turbojet, OffDesignMatcher, ComponentMap,
    TwoLagCascadeTransient, BleedLimiter, SurgeLimiter, AsymmetricLag,
)

_HERE = os.path.dirname(os.path.abspath(__file__))
GOLDEN_PATH = os.path.join(_HERE, "golden", "numeric_fingerprint.json")

# --------------------------------------------------------------------------- tolerances
# tol = one round decade above the measured CPython-vs-PyPy drift (see the module docstring).
# 0.0 means BIT-EQUALITY is asserted, because zero values differed across interpreters.
TOL = {
    "cpg": 0.0,      # measured EXACT — 0 of 96 values differed
    "r66": 0.0,      # measured EXACT — 0 of 6 152 (6 140 floats + 12 discrete readings) differed
    "A":   1e-10,    # measured drift 6.6e-12
    "B":   1e-11,    # measured drift 1.0e-12
    "C":   1e-13,    # measured drift 2.4e-15
    "D":   1e-7,     # measured drift 1.0e-8
    "E":   1e-9,     # measured drift 6.6e-11
    "F":   1e-4,     # measured drift 3.7e-6  <- the WEAKEST arm of slice 1
    # ---------------- SLICE 2: the rungs 3-30 DIAGNOSTIC ladder (2026-07-31) ----------------
    # Same rule, same measurement (`M:\claud_projects\temp\pypy-fingerprint\slice2.py` +
    # `compare2.py`, 1 661 values). Keyed BY RUNG, not by letter: a failure has to say which
    # rung moved. Every one of these consumes 1.3-9.6% of its band — see § SLICE 2 below.
    "prop": 1e-10,   # measured drift 8.9e-12   the gas property layer, rungs 3/4/5/6
    "r7":   1e-13,   # measured drift 2.1e-15   thermal_nox (+ rung-19 super-eq-O / prompt)
    "r8":   1e-13,   # measured drift 2.4e-15   zoned_nox mixed-out, the rung-9 phi bell
    "r10":  1e-13,   # measured drift 1.6e-15   the finite-rate quench (tau_q)
    "r11":  1e-13,   # measured drift 1.3e-15   JetMixing — tau_q DERIVED from J
    "r12":  1e-13,   # measured drift 1.4e-15   Unmixedness
    "r13":  1e-13,   # measured drift 1.9e-15   MixingPDF
    "r14":  1e-9,    # measured drift 9.7e-11   nozzle_flow (frozen-vs-equilibrium bracket)
    "r15":  1e-13,   # measured drift 1.8e-15   QuenchPDF
    "r16":  1e-13,   # measured drift 1.7e-15   PocketQuenchPDF (+ the rung-20/21 lift)
    "r17":  1e-9,    # measured drift 9.7e-11   exhaust_no_clamp — inherits r14's nozzle
    "r18":  1e-13,   # measured drift 1.3e-15   TransportedPDF (the NEGATIVE rung's kernel)
    "r22":  1e-13,   # measured drift 1.3e-15   SpatialPDF
    "r23":  1e-13,   # measured drift 1.6e-15   SpatialDwellPDF
    "r24":  1e-12,   # measured drift 3.3e-14   SpatialLocalPDF
    "r25":  1e-4,    # measured drift 2.0e-6    finite_rate_nozzle <- joint-WEAKEST; see below
    "r27":  1e-8,    # measured drift 1.8e-10   no_freeze_out_nozzle
    "r28":  1e-5,    # measured drift 6.8e-7    coupled_no_freeze_out_nozzle
}

# --------------------------------------------------------------------------- shared conditions
FLIGHT = FlightCondition(T0=250.0, p0=50_000.0, M0=0.85)
PI_C, TT4 = 10.0, 1500.0
LOSSES = dict(pi_d=0.97, eta_c=0.88, eta_b=0.99, pi_b=0.96, eta_t=0.90, eta_m=0.99, pi_n=0.98)


def _cpg_gas():
    """The self-consistent CPG dual gas rungs 31-66 use: R_t = (g-1)/g*cp_t exactly."""
    g, cp = 1.3, 1239.0
    return Gas(gamma_c=1.4, cp_c=1004.0, R_c=286.9,
               gamma_t=g, cp_t=cp, R_t=(g - 1.0) / g * cp, hPR=42.8e6)


def _floats_of(obj, prefix, out):
    """Every public float attribute of a result object, sorted for determinism.

    An attribute that RAISES is PINNED as raising, not silently skipped. Recording the exception
    TYPE as a pinned value means the day an attribute starts or stops raising reads as the SHAPE
    change it is, rather than as a quietly-dropped attribute.

    The mechanism earned itself immediately, and that case is now historical: the slice-2 probe
    found `CoupledNOFreezeOutState.no_collapse_ratio` (rung 28) reading `self.x_no_e_entry`, a
    field copied from `NozzleFlowState` that the dataclass does not have — so it raised
    AttributeError unconditionally, and nothing called it. Slice 2 disclosed it here rather than
    repairing production code out of scope; it was deleted (not repaired — the repair would have
    been vacuous, see the comment at its former site in `gas.py`) in the slice-4 commit, and the
    two `r28.*!raises` keys left the goldens in that regeneration. The mechanism stays: it is the
    only thing in the gate that can see an attribute change its FAILURE behaviour."""
    for attr in sorted(a for a in dir(obj) if not a.startswith("_")):
        try:
            v = getattr(obj, attr)
        except Exception as exc:                     # noqa: BLE001 — pinning the failure IS the point
            out[f"{prefix}.{attr}!raises"] = type(exc).__name__
            continue
        if isinstance(v, float):
            out[f"{prefix}.{attr}"] = v


# --------------------------------------------------------------------------- kernels
# Each returns {name: value}. Values are float (compared at the kernel's tolerance) or
# int/list (compared EXACTLY — these are the discrete readings, where "close" is meaningless).

def kernel_cpg():
    """The CPG structural ladder: design run + the rung-31 off-design throttle sweep."""
    out = {}
    design = build_turbojet(_cpg_gas(), PI_C, TT4, FLIGHT.p0, nozzle_convergent=True, **LOSSES)
    r = design.run(FLIGHT, 1.0)
    for k in sorted(r.stations):
        out[f"design.st{k}.Tt"] = r.stations[k].Tt
        out[f"design.st{k}.pt"] = r.stations[k].pt
    m = OffDesignMatcher(design, FLIGHT, 1.0)
    for Tt4 in (1500.0, 1400.0, 1300.0, 1200.0, 1100.0, 1000.0):
        _floats_of(m.match(FLIGHT, Tt4), f"od{int(Tt4)}", out)
    return out


def kernel_r66():
    """The rung-66 two-lag cascade march, both clocks armed — trajectory AND discrete events."""
    PI_LPC, PI_HPC = 3.0, 6.0
    REAL = dict(pi_d=0.97, eta_lpc=0.90, eta_hpc=0.88, eta_b=0.99, pi_b=0.96,
                eta_hpt=0.92, eta_lpt=0.90, eta_m=0.99, pi_n=0.98)
    FLOOR, PHI, B = 0.55, 0.80, 0.10
    LO, HI, DS, SETTLE, R = 1000.0, 1400.0, 0.005, 1.2, 0.5
    lp = ComponentMap(a=0.20, b=0.05, sigma=0.1, l=0.7).with_phi_surge(FLOOR)
    hp = ComponentMap(a=0.08, b=0.15, sigma=0.1, l=1.0).with_phi_surge(FLOOR)
    design = build_two_spool_turbojet(_cpg_gas(), PI_LPC, PI_HPC, TT4, FLIGHT.p0,
                                      nozzle_convergent=True, **REAL)
    m = TwoLagCascadeTransient(design, FLIGHT, 1.0, map_lp=lp, map_hp=hp, rho=1.0,
                               bleed_lim=BleedLimiter(phi_lim=PHI, b_max=B, tau=0.05))
    traj = m._stator_march(FLIGHT, LO, HI, R, SETTLE, DS,
                           surge=SurgeLimiter.from_margin(lp, "lp", PHI / FLOOR - 1.0),
                           lag=AsymmetricLag(tau_att=0.05, tau_rel=0.15))[0]

    out = {"rows": len(traj)}
    keys = [k for k in sorted(traj[0]) if isinstance(traj[0][k], float)]
    out["keys"] = keys                                   # pinned: a moved key is a SHAPE change
    for i, p in enumerate(traj):
        for k in keys:
            out[f"t[{i}].{k}"] = p[k]
    # The DISCRETE readings — where a last-bit shift would show up as a JUMP, not a drift.
    for k in ("phi_lp", "phi_hp"):
        if k in keys:
            j = min(range(len(traj)), key=lambda i: traj[i][k])
            out[f"argmin.{k}"] = j
            out[f"min.{k}"] = traj[j][k]
    for k in ("g", "b", "mf", "Tt4"):
        if k in keys:
            out[f"edges.{k}"] = [i for i in range(1, len(traj))
                                 if (traj[i][k] > 0.0) != (traj[i - 1][k] > 0.0)]
            out[f"argmax.{k}"] = max(range(len(traj)), key=lambda i: traj[i][k])
    return out


def _equilibrium_design():
    """The shared equilibrium design run behind kernels A / C / D / E / F."""
    gas = Gas.reacting_equilibrium()
    res = build_turbojet(gas, PI_C, TT4, FLIGHT.p0, **LOSSES).run(FLIGHT, 50.0)
    return gas, res


def kernel_A():
    """Equilibrium design point — the _equil_solve Newton and its _gauss_solve linear algebra."""
    gas, res = _equilibrium_design()
    out = {}
    for k in sorted(res.stations):
        st = res.stations[k]
        out[f"st{k}.Tt"], out[f"st{k}.pt"], out[f"st{k}.far"] = st.Tt, st.pt, st.far
    for attr in ("thrust", "tsfc", "f", "eta_th", "eta_p", "eta_o", "v9"):
        if hasattr(res, attr):
            out[attr] = getattr(res, attr)
    return out


def kernel_B():
    """Mixing-PDF geometry — the rung-22/24 cross-plane integrals (erf, log1p, naive sums)."""
    mix = JetMixing(J=16.0, C_e=0.20, U_c=75.0, shape_n=2.0)
    g_field, tau_of_xi, F = _spatial_local_field(0.02718, 1.5, 0.0625, 0.10, 16.0, mix.tau_q,
                                                 ny=32, nz=32)
    out = {"g_spatial": g_field, "F_shape": F, "tau_q": mix.tau_q}
    for k in range(21):                                  # tau(xi) sampled across the whole bell
        out[f"tau_of_xi[{k}]"] = float(tau_of_xi(0.001 + k * (0.070 - 0.001) / 20.0))
    for JJ in (4.0, 9.0, 36.0, 64.0):                    # F over J: the U-shape the rung reads
        gj, _, Fj = _spatial_local_field(0.02718, 1.5, 0.0625, 0.10, JJ,
                                         JetMixing(J=JJ, C_e=0.20, U_c=75.0, shape_n=2.0).tau_q,
                                         ny=32, nz=32)
        out[f"J{int(JJ)}.g"], out[f"J{int(JJ)}.F"] = gj, Fj
    return out


def kernel_C():
    """Zoned NOx chemistry — Arrhenius exp/log through the quench march."""
    gas, res = _equilibrium_design()
    st3, st4 = res.stations["3"], res.stations["4"]
    z = gas.zoned_nox(st4.far, st3.Tt, st4.Tt, st4.pt, tau=3e-3, phi_primary=1.5,
                      mixing=JetMixing(J=16.0, C_e=0.20, U_c=75.0, shape_n=2.0),
                      quench_ngrid=12, quench_nsteps=40)
    out = {}
    _floats_of(z, "z", out)
    return out


def kernel_D():
    """Shifting turbine — the _work_limited_expand bisection (pr_t, powers, tau**0.5)."""
    gas, res = _equilibrium_design()
    st4 = res.stations["4"]
    delta_h = gas.h_t(st4.Tt, st4.far) - gas.h_t(res.stations["5"].Tt, st4.far)
    out = {}
    _floats_of(gas.shifting_turbine(st4.far, st4.Tt, st4.pt, delta_h), "sh", out)
    return out


def kernel_E():
    """Off-design matcher ON THE EQUILIBRIUM GAS — the same solver as `cpg`, different gas."""
    gas = Gas.reacting_equilibrium()
    design = build_turbojet(gas, PI_C, TT4, FLIGHT.p0, nozzle_convergent=True, **LOSSES)
    m = OffDesignMatcher(design, FLIGHT, 1.0)
    out = {}
    for Tt4 in (1500.0, 1300.0, 1100.0):
        _floats_of(m.match(FLIGHT, Tt4), f"{int(Tt4)}", out)
    return out


def kernel_F():
    """Freeze-out nozzle march — rung 26's local Da(T,p) clock. The widest-drift kernel."""
    gas, res = _equilibrium_design()
    st4, st5 = res.stations["4"], res.stations["5"]
    fo = gas.freeze_out_nozzle(st4.far, st4.Tt, st4.pt, st5.Tt, st5.pt, FLIGHT.p0,
                               freeze_out=FreezeOut(L=0.3))
    out = {}
    _floats_of(fo, "fo", out)
    return out


# ===========================================================================================
# SLICE 2 — the rungs 3-30 DIAGNOSTIC ladder
# ===========================================================================================
# RESOLUTION, disclosed. These kernels run at REDUCED quadrature, not at the resolution a spec
# quotes: the mixing closures at full config defaults are the project's most expensive code
# (rung 24's `test_ei_stays_monotone` is ~518 s for ONE gate). The anchor CONFIGURATION is kept
# — S=0.0625, the J values, phi_p=1.5, the design point — and only the node counts are cut.
#
# ** A GREEN ARM HERE DOES NOT GUARD THE SPEC'S QUOTED DIGIT. ** It guards the kernel's
# arithmetic at this resolution, which is what a drift detector needs. Said plainly because the
# reverse reading is the tempting one.
#
# The reduction was CHECKED, not assumed. The mechanism behind the equilibrium-side drift is
# naive `sum()` reassociation, whose error grows with TERM COUNT — so a reduced probe could
# under-report. Re-measured at 4x the terms (2x n_bell, 2x n_quad, 4x cross-plane cells) on
# r13/r18/r22/r24: see § SLICE 2 in the module docstring for the result.
_NG, _NS = 24, 200        # zoned_nox quench grid / steps  (defaults 240 / 2000)
_NB, _NQ = 24, 48         # PDF bell / quadrature nodes    (defaults 200 / 200, or 120 / 160)
_NXY = 16                 # cross-plane ny = nz            (defaults 48, or 40)
_NT = 12                  # dwell time nodes               (default 32)
_PDF = dict(n_bell=_NB, n_quad=_NQ)
_XY = dict(ny=_NXY, nz=_NXY)
_MIX = dict(C_e=0.20, U_c=75.0, shape_n=2.0)      # the rung-11 jet, J passed per call


def _dp():
    """The shared equilibrium design point, as (gas, far, Tt3, Tt4, pt4, Tt5, pt5)."""
    gas, res = _equilibrium_design()
    st3, st4, st5 = res.stations["3"], res.stations["4"], res.stations["5"]
    return gas, st4.far, st3.Tt, st4.Tt, st4.pt, st5.Tt, st5.pt


def _zoned(cases):
    """zoned_nox at the shared design point, rung 9's rich primary, one closure per case."""
    gas, far, Tt3, Tt4, pt4, _, _ = _dp()
    out = {}
    for tag, extra in cases.items():
        kw = dict(phi_primary=1.5, tau=3e-3, quench_ngrid=_NG, quench_nsteps=_NS)
        kw.update(extra)
        _floats_of(gas.zoned_nox(far, Tt3, Tt4, pt4, **kw), tag, out)
    return out


def kernel_prop():
    """RUNGS 3/4/5/6 — the GAS PROPERTY LAYER, under every factory.

    The substrate every other arm stands on: the NASA cp/h/pr integrals and their inverses,
    plus Fork B's absolute-enthalpy interface and the rung-6 equilibrium composition solve.
    It buys SEPARABILITY — this arm red means the PRIMITIVE layer moved; a diagnostic arm red
    with this one green means the diagnostic moved. Milliseconds; no cycle run."""
    TS = [250.0, 500.0, 800.0, 1200.0, 1500.0, 1800.0, 2200.0, 2800.0]
    FARS = [0.0, 0.010, 0.02718, 0.040]
    out = {}
    gases = {"tpg": Gas.thermally_perfect(),
             "r4": Gas.reacting(f_design=0.02718),
             "r5": Gas.reacting_forkb(f_design=0.02718)}
    eq = Gas.reacting_equilibrium(f_design=0.02718)
    eq.freeze_equilibrium(0.02718, 1500.0, 1.4e6)     # an equilibrium hot section must be frozen
    gases["r6"] = eq

    for gname, g in gases.items():
        for T in TS:
            out[f"{gname}.cp_c({T:g})"] = g.cp_c_at(T)
            out[f"{gname}.h_c({T:g})"] = g.h_c(T)
            out[f"{gname}.pr_c({T:g})"] = g.pr_c(T)
            out[f"{gname}.gam_c({T:g})"] = g.gamma_c_at(T)
            out[f"{gname}.T_of_h_c({T:g})"] = g.T_from_h_c(g.h_c(T))
            out[f"{gname}.T_of_pr_c({T:g})"] = g.T_from_pr_c(g.pr_c(T))
        for far in ([0.02718] if gname == "r6" else FARS):    # r6 is frozen at ONE far
            out[f"{gname}.R_t({far:g})"] = g.R_t_at(far)
            for T in TS:
                out[f"{gname}.cp_t({T:g},{far:g})"] = g.cp_t_at(T, far)
                out[f"{gname}.h_t({T:g},{far:g})"] = g.h_t(T, far)
                out[f"{gname}.pr_t({T:g},{far:g})"] = g.pr_t(T, far)
                out[f"{gname}.gam_t({T:g},{far:g})"] = g.gamma_t_at(T, far)
                out[f"{gname}.T_of_h_t({T:g},{far:g})"] = g.T_from_h_t(g.h_t(T, far), far)
                out[f"{gname}.T_of_pr_t({T:g},{far:g})"] = g.T_from_pr_t(g.pr_t(T, far), far)

    fb = gases["r5"]                                          # rung 5's absolute-enthalpy side
    out["r5.lhv"], out["r5.f_stoich"] = fb.lhv, fb.f_stoich_lean
    out["r5.hf_fuel_mass"] = fb.hf_fuel_mass
    for far in FARS:
        out[f"r5.hf_products({far:g})"] = fb.hf_products_mass(far)
        for T in (1200.0, 1800.0, 2400.0):
            out[f"r5.h_t_abs({T:g},{far:g})"] = fb.h_t_abs(T, far)
    for T in (1200.0, 1800.0, 2400.0):
        out[f"r6.h_air_B({T:g})"] = eq.h_air_abs_B(T)
    for far, T, p in ((0.010, 1800.0, 1.4e6), (0.02718, 2400.0, 1.4e6), (0.02718, 2400.0, 3.0e5)):
        comp = eq.equilibrium_composition(far, T, p)          # the rung-6 Kp solve itself
        for s in sorted(comp):
            out[f"r6.comp({far:g},{T:g},{p:g}).{s}"] = comp[s]
        out[f"r6.h_prod_B({far:g},{T:g},{p:g})"] = eq.h_products_abs_B(comp, T)
    return out


def kernel_r7():
    """RUNG 7 (+19) — thermal_nox: extended Zeldovich on the equilibrium pool. Plain, with the
    rung-19 super-equilibrium-O lift, with prompt NO, and both. Pure Arrhenius exp/log."""
    gas, far, _, _, pt4, _, _ = _dp()
    out = {}
    for tag, kw in (("plain", {}), ("supereq", dict(super_eq_o=True)),
                    ("prompt", dict(prompt=PromptNO(), phi=1.0)),
                    ("both", dict(super_eq_o=True, prompt=PromptNO(), phi=1.2))):
        _floats_of(gas.thermal_nox(far, 2200.0, pt4, tau=3e-3, **kw), tag, out)
    for T in (1800.0, 2000.0, 2400.0):                # the T-sensitivity the rung reads
        _floats_of(gas.thermal_nox(far, T, pt4, tau=3e-3), f"T{int(T)}", out)
    return out


def kernel_r8():
    """RUNGS 8/9 — zoned_nox MIXED-OUT, swept over phi_primary: the rung-9 bell (lean -> the
    near-stoich peak -> the rich collapse), with no quench closure in the way."""
    return _zoned({f"phi{phi:g}": dict(phi_primary=phi) for phi in (0.8, 1.0, 1.2, 1.5, 2.0)})


def kernel_r10():
    """RUNG 10 — the FINITE-RATE quench: tau_q resolves the dilution in time, so a rich
    primary's T rises back through the stoich peak and RE-MAKES NO."""
    return _zoned({f"tq{tq:g}": dict(tau_q=tq) for tq in (1e-3, 3e-3)})


def kernel_r11():
    """RUNG 11 — JetMixing DERIVES tau_q from the jet momentum-flux ratio J (the monotone,
    mean-field sweep)."""
    return _zoned({f"J{int(J)}": dict(mixing=JetMixing(J=J, **_MIX))
                         for J in (4.0, 16.0, 64.0)})


def kernel_r12():
    """RUNG 12 — Unmixedness: the bulk + under-mixed-core split that turns the J-sweep back up
    and pins the minimum at C_opt."""
    return _zoned({f"J{int(J)}": dict(mixing=JetMixing(J=J, **_MIX),
                                            unmixedness=Unmixedness(S=0.0625))
                         for J in (4.0, 16.0, 64.0)})


def kernel_r13():
    """RUNG 13 — MixingPDF: the mean-preserving beta-PDF over the ideal bell."""
    return _zoned({f"J{int(J)}": dict(mixing=JetMixing(J=J, **_MIX),
                                            pdf=MixingPDF(S=0.0625, **_PDF))
                         for J in (4.0, 16.0)})


def kernel_r14():
    """RUNG 14 — nozzle_flow: the frozen-vs-shifting-equilibrium exit-velocity bracket, and the
    dropped-clamp collapse ratio every rung 17+ number reads off it."""
    gas, far, _, Tt4, pt4, Tt5, pt5 = _dp()
    out = {}
    _floats_of(gas.nozzle_flow(far, Tt4, pt4, Tt5, pt5, FLIGHT.p0), "nf", out)
    return out


def kernel_r15():
    """RUNG 15 — QuenchPDF: rung 13's PDF carried through the finite quench chain (both mixing
    mechanisms combined -> a finite floor)."""
    return _zoned({f"J{int(J)}": dict(mixing=JetMixing(J=J, **_MIX),
                                            pdf_quench=QuenchPDF(S=0.0625, **_PDF))
                         for J in (4.0, 16.0)})


def kernel_r16():
    """RUNG 16 (+20/21) — PocketQuenchPDF: each pocket through its OWN quench, with and without
    the rung-19/20/21 super-equilibrium-O lift threaded through those same integrals."""
    return _zoned({"J4": dict(mixing=JetMixing(J=4.0, **_MIX),
                                    pocket_quench=PocketQuenchPDF(S=0.0625, **_PDF)),
                         "J16": dict(mixing=JetMixing(J=16.0, **_MIX),
                                     pocket_quench=PocketQuenchPDF(S=0.0625, **_PDF)),
                         "J16.seq": dict(mixing=JetMixing(J=16.0, **_MIX), super_eq_o=True,
                                         pocket_quench=PocketQuenchPDF(S=0.0625, **_PDF))})


def kernel_r17():
    """RUNG 17 — exhaust_no_clamp: the three mixing-fidelity models (mixed-out / bulk quench /
    per-pocket) through the SAME rung-14 nozzle, and the clamp margin each one reads."""
    gas, far, Tt3, Tt4, pt4, Tt5, pt5 = _dp()
    out = {}
    c = gas.exhaust_no_clamp(far, Tt3, Tt4, pt4, Tt5, pt5, FLIGHT.p0, phi_primary=1.5,
                             mixing=JetMixing(J=16.0, **_MIX),
                             pocket_quench=PocketQuenchPDF(S=0.0625, **_PDF),
                             quench_ngrid=_NG, quench_nsteps=_NS)
    _floats_of(c, "clamp", out)
    return out


def kernel_r18():
    """RUNG 18 — TransportedPDF: the variance-decay ODE. The rung is a NEGATIVE, but its kernel
    is live code and carries quoted digits, so it is pinned like any other."""
    return _zoned({f"J{int(J)}": dict(mixing=JetMixing(J=J, **_MIX),
                                            transported=TransportedPDF(S=0.0625, **_PDF))
                         for J in (4.0, 16.0)})


def kernel_r22():
    """RUNG 22 — SpatialPDF: the resolved y-z cross-plane that makes C_opt an OUTPUT."""
    return _zoned({f"J{int(J)}": dict(mixing=JetMixing(J=J, **_MIX),
                                            spatial=SpatialPDF(S=0.0625, **_PDF, **_XY))
                         for J in (4.0, 16.0)})


def kernel_r23():
    """RUNG 23 — SpatialDwellPDF: the cross-plane developed in TIME (the xi-tau correlation that
    ADDS NO)."""
    return _zoned({f"J{int(J)}": dict(
        mixing=JetMixing(J=J, **_MIX),
        spatial_dwell=SpatialDwellPDF(S=0.0625, nt=_NT, **_PDF, **_XY)) for J in (4.0, 16.0)})


def kernel_r24():
    """RUNG 24 — SpatialLocalPDF: each cell its OWN rate, so tau_mix cancels and F(C) goes
    U-shaped with its minimum AT the derived C_opt."""
    return _zoned({f"J{int(J)}": dict(mixing=JetMixing(J=J, **_MIX),
                                            spatial_local=SpatialLocalPDF(S=0.0625, **_PDF, **_XY))
                         for J in (4.0, 16.0)})


def kernel_r25():
    """RUNG 25 — finite_rate_nozzle: the Damkoehler flow between rung-14's bounds, across the
    three-state (F / I / R) picture. Its entropy differences are differences-of-near-equals,
    which is why this arm's band is as wide as kernel F's."""
    gas, far, _, Tt4, pt4, Tt5, pt5 = _dp()
    out = {}
    for Da in (0.1, 1.0, 10.0):
        _floats_of(gas.finite_rate_nozzle(far, Tt4, pt4, Tt5, pt5, FLIGHT.p0,
                                          finite_rate=FiniteRate(Da=Da)), f"Da{Da:g}", out)
    return out


def kernel_r27():
    """RUNG 27 — no_freeze_out_nozzle: the clock under the frozen-NO assumption every NO number
    since rung 7 rides on."""
    gas, far, Tt3, Tt4, pt4, Tt5, pt5 = _dp()
    out = {}
    _floats_of(gas.no_freeze_out_nozzle(far, Tt3, Tt4, pt4, Tt5, pt5, FLIGHT.p0,
                                        phi_primary=1.5,
                                        no_freeze_out=NOFreezeOut(L=0.3)), "nfo", out)
    return out


def kernel_r28():
    """RUNG 28 — coupled_no_freeze_out_nozzle, COUPLED and UNCOUPLED: rung 27's clock on rung
    26's relaxing pool, and the kill test both of rung 28's corrections ride on."""
    gas, far, Tt3, Tt4, pt4, Tt5, pt5 = _dp()
    out = {}
    for couple in (True, False):
        _floats_of(gas.coupled_no_freeze_out_nozzle(
            far, Tt3, Tt4, pt4, Tt5, pt5, FLIGHT.p0, phi_primary=1.5,
            coupled=CoupledNOFreezeOut(L=0.3), couple=couple),
            "on" if couple else "off", out)
    return out


KERNELS = {"cpg": kernel_cpg, "r66": kernel_r66, "A": kernel_A, "B": kernel_B,
           "C": kernel_C, "D": kernel_D, "E": kernel_E, "F": kernel_F,
           # slice 2 — the rungs 3-30 diagnostic ladder
           "prop": kernel_prop, "r7": kernel_r7, "r8": kernel_r8, "r10": kernel_r10,
           "r11": kernel_r11, "r12": kernel_r12, "r13": kernel_r13, "r14": kernel_r14,
           "r15": kernel_r15, "r16": kernel_r16, "r17": kernel_r17, "r18": kernel_r18,
           "r22": kernel_r22, "r23": kernel_r23, "r24": kernel_r24, "r25": kernel_r25,
           "r27": kernel_r27, "r28": kernel_r28}


# --------------------------------------------------------------------------- encode / compare
# Floats round-trip through .hex() EXACTLY; repr() at 17 digits also round-trips but hex makes a
# last-bit change visible to the eye in the committed diff, which repr does not.
def _encode(v):
    return {"f": v.hex()} if isinstance(v, float) else v


def _decode(v):
    return float.fromhex(v["f"]) if isinstance(v, dict) and "f" in v else v


def _close(a, b, tol):
    """`a` measured, `b` golden. tol == 0.0 means bit-equality."""
    if a == b:
        return True, 0.0
    if not isinstance(a, float) or not isinstance(b, float):
        return False, float("inf")
    err = abs(a - b) / abs(b) if b != 0.0 else abs(a)
    return (err <= tol) if tol > 0.0 else False, err


def _show(v):
    return f"{v!r}  [{v.hex()}]" if isinstance(v, float) else repr(v)


def _load_golden():
    with open(GOLDEN_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def _check(name):
    """Shape first, then values — a signature drift must not read as a numeric regression."""
    golden = _load_golden()
    assert name in golden["kernels"], (
        f"kernel {name!r} has no golden. Regenerate deliberately — see the module docstring.")
    want = {k: _decode(v) for k, v in golden["kernels"][name].items()}
    got = KERNELS[name]()

    missing, extra = sorted(set(want) - set(got)), sorted(set(got) - set(want))
    assert not missing and not extra, (
        f"kernel {name!r}: THE KERNEL'S API CHANGED, NOT ITS ARITHMETIC — this is a signature "
        f"drift, not a numeric regression.\n"
        f"  in the golden but no longer produced ({len(missing)}): {missing[:8]}\n"
        f"  newly produced, not in the golden ({len(extra)}): {extra[:8]}\n"
        f"Fix the probe to match the new API; the VALUES must be unchanged.")

    tol = TOL[name]
    bad = []
    for k in sorted(want):
        ok, err = _close(got[k], want[k], tol)
        if not ok:
            bad.append((k, want[k], got[k], err))
    assert not bad, (
        f"kernel {name!r}: {len(bad)} of {len(want)} values moved beyond tol={tol:g}"
        + (" (BIT-EQUALITY asserted — this kernel is measured exact)" if tol == 0.0 else "")
        + "\n" + "\n".join(
            # hex alongside repr: on the bit-exact arms the interesting failure is a 1-ulp shift,
            # and "...ff4p+9 vs ...ff5p+9" says that at a glance where two 17-digit reprs do not.
            # A DISCRETE reading (an argmin row, a limiter edge list) has no meaningful relative
            # error, and printing "inf" beside it buries the most important failure this module
            # can report — a limiter engagement row moving is exactly what rungs 46-66 measure.
            f"  {k}\n    golden {_show(w)}\n    actual {_show(g)}"
            + (f"\n    rel err {e:.3e}" if e != float("inf") else
               "\n    ^ a DISCRETE reading MOVED — not a drift. Either a min-select crossing / "
               "limiter engage-release row is at a different index (the rungs 46-66 failure "
               "mode), or a `!raises` attribute changed which exception it raises.")
            for k, w, g, e in bad[:5])
        + (f"\n  ... and {len(bad) - 5} more" if len(bad) > 5 else "")
        + "\nDo NOT regenerate reflexively — work the procedure in this module's docstring.")


# --------------------------------------------------------------------------- the gates
# The `test_golden_fingerprint_*` / `test_golden_kernel_*` split is now purely a COST label: the
# first are cheap and carry no marker, the second are `@pytest.mark.slow` so `-m "not slow"` can
# skip them while iterating. Both run on a plain `pytest`, which runs everything.
# HISTORY (it explains the naming, which is otherwise arbitrary): the prefix used to trigger
# `conftest._is_spine`, a force-run override that kept these absolute-value gates inside a FAST
# DEFAULT that would otherwise have deselected them. The default was inverted 2026-07-31 and the
# override deleted — see conftest.py. The names were left alone; only their meaning narrowed.

def test_golden_fingerprint_cpg():
    """The CPG structural ladder — rungs 31-66's actual path. Bit-equality."""
    _check("cpg")


def test_golden_fingerprint_r66():
    """The rung-66 cascade: 6 152 trajectory floats + every discrete event. Bit-equality."""
    _check("r66")


def test_golden_fingerprint_A_equilibrium_cycle():
    _check("A")


def test_golden_fingerprint_B_mixing_pdf():
    _check("B")


def test_golden_fingerprint_C_zoned_nox():
    _check("C")


def test_golden_fingerprint_D_shifting_turbine():
    _check("D")


def test_golden_fingerprint_E_offdesign_equilibrium():
    _check("E")


def test_golden_fingerprint_F_freeze_out():
    _check("F")


# ------------------------------------------------------------------ slice 2, the CHEAP arms
# `test_golden_fingerprint_*` == unmarked, so these survive the `-m "not slow"` opt-out too.
# Given ONLY to arms measured <= 2 s idle, which is what keeps that opt-out worth typing.

def test_golden_fingerprint_prop_gas_properties():
    """RUNGS 3-6, the property layer. The separability arm: red here means the PRIMITIVE moved."""
    _check("prop")


def test_golden_fingerprint_r7_thermal_nox():
    _check("r7")


def test_golden_fingerprint_r8_zoned_nox_bell():
    _check("r8")


def test_golden_fingerprint_r10_finite_rate_quench():
    _check("r10")


def test_golden_fingerprint_r14_nozzle_flow():
    _check("r14")


def test_golden_fingerprint_r25_finite_rate_nozzle():
    _check("r25")


def test_golden_fingerprint_r27_no_freeze_out():
    _check("r27")


def test_golden_fingerprint_r28_coupled_no_march():
    _check("r28")


# ------------------------------------------------------------------ slice 2, the COSTLY arms
# Deliberately NOT `test_golden_fingerprint_*`: these are the mixing closures, the costliest arms
# in the module, so they are the ones `-m "not slow"` should shed. The three heaviest carry an
# explicit `@pytest.mark.slow` (r16 9.5 / r23 11.9 / r24 11.9 s on PyPy); the rest are cheap
# enough to leave unmarked. All of them run on a plain `pytest` either way — under the retired
# tiering this block had to argue that `--affected` would reach them, and it no longer does.
# Measured idle, CPython: r11 2.4 / r12 2.4 / r13 3.1 / r15 3.1 / r18 4.5 / r22 4.6 / r17 16.4 /
# r16 46.5 / r23 60.5 / r24 60.5 s. The wall-clock pole is rung 24's own `test_ei_stays_monotone`,
# not anything here.

def test_golden_kernel_r11_jet_mixing():
    _check("r11")


def test_golden_kernel_r12_unmixedness():
    _check("r12")


def test_golden_kernel_r13_mixing_pdf():
    _check("r13")


def test_golden_kernel_r15_quench_pdf():
    _check("r15")


@pytest.mark.slow
def test_golden_kernel_r16_pocket_quench_pdf():
    _check("r16")


def test_golden_kernel_r17_exhaust_no_clamp():
    _check("r17")


def test_golden_kernel_r18_transported_pdf():
    _check("r18")


def test_golden_kernel_r22_spatial_pdf():
    _check("r22")


@pytest.mark.slow
def test_golden_kernel_r23_spatial_dwell_pdf():
    _check("r23")


@pytest.mark.slow
def test_golden_kernel_r24_spatial_local_pdf():
    _check("r24")


def test_golden_file_declares_its_provenance():
    """The goldens' whole value is being CPython's. If the meta block ever stops saying so —
    because someone regenerated under another interpreter — the anchor is gone and this file
    silently degrades into 'the current interpreter agrees with itself'. Guard it.

    HONEST SCOPE: this catches regeneration under a DIFFERENT interpreter only. Regenerating
    under CPython writes 'cpython' and sails through — see the procedure in the module docstring,
    which is the only thing standing between a real regression and a silently replaced anchor."""
    meta = _load_golden()["meta"]
    assert meta["implementation"] == "cpython", (
        f"the golden file was generated by {meta['implementation']!r}, not CPython. "
        "Its entire value is being an INDEPENDENT anchor — see the module docstring. "
        "Restore the CPython-generated file from git; do not accept this.")
    for k in ("version", "generated", "repo_sha"):
        assert meta.get(k), f"golden meta is missing {k!r} — provenance must be complete"


def test_every_kernel_has_a_disclosed_tolerance():
    """No kernel may be compared at a tolerance that is not written down beside its measurement."""
    golden = _load_golden()
    assert set(KERNELS) == set(TOL) == set(golden["kernels"]), (
        f"kernels {sorted(KERNELS)}, tolerances {sorted(TOL)}, "
        f"goldens {sorted(golden['kernels'])} — these three sets must agree exactly")


def test_every_kernel_is_actually_GATED():
    """The three sets above can all agree while a kernel has NO test function calling `_check`
    on it — it would be generated, pinned, counted in the value total, and never verified. At
    eight arms that was eyeball-checkable; at twenty-six across two naming conventions it is not,
    and the failure is silent in the direction that matters (a green suite hiding an unchecked
    kernel). So read the gates' own source and assert every kernel is reached by one."""
    import inspect
    import re

    gated = set()
    for name, fn in globals().items():
        if name.startswith("test_") and callable(fn) and name != "test_every_kernel_is_actually_GATED":
            gated |= set(re.findall(r'_check\("([^"]+)"\)', inspect.getsource(fn)))
    ungated = sorted(set(KERNELS) - gated)
    assert not ungated, (
        f"{len(ungated)} kernel(s) are pinned in the golden but no test checks them: {ungated}. "
        "Add a gate — `test_golden_fingerprint_*` if the arm is <= 2 s idle, "
        "`test_golden_kernel_*` (+ `@pytest.mark.slow` if heavy) otherwise.")
    assert not (gated - set(KERNELS)), (
        f"a gate calls _check on a kernel that does not exist: {sorted(gated - set(KERNELS))}")


# --------------------------------------------------------------------------- regeneration
def _regenerate():
    """Print every changing value, THEN write. The printed diff is the point of the flag."""
    import subprocess
    import time

    try:
        old = _load_golden()["kernels"]
    except (OSError, ValueError):
        old = {}
    new = {}
    for name, fn in KERNELS.items():
        print(f"  running kernel {name} ...", flush=True)
        new[name] = {k: _encode(v) for k, v in fn().items()}

    # TWO PASSES, and the order is the whole point. A regeneration that ADDS a kernel (slice 2 of
    # the PyPy plan adds ~10) emits thousands of pure additions; a single capped list would spend
    # its budget on those and never reach a MOVED value — which is the only kind that can destroy
    # the anchor. So moved-values print FIRST and UNCAPPED; additions print after, capped.
    moved, added, removed = [], 0, []
    for name in sorted(new):
        prev, cur = old.get(name, {}), new[name]
        for k in sorted(set(prev) | set(cur)):
            if k not in prev:
                added += 1
                continue
            if k not in cur:
                removed.append(f"{name}.{k}")
                continue
            a, b = _decode(prev[k]), _decode(cur[k])
            if a != b:
                moved.append((f"{name}.{k}", a, b))
    for name in sorted(set(old) - set(new)):
        removed.extend(f"{name}.{k}" for k in sorted(old[name]))

    if moved:
        print(f"\n  !!! {len(moved)} EXISTING value(s) MOVED — this is the diff that matters:")
        for k, a, b in moved:
            print(f"    {k}\n      was {a!r}\n      now {b!r}")
    if removed:
        print(f"\n  !!! {len(removed)} value(s) DISAPPEARED (a probe's shape changed): "
              f"{removed[:10]}" + (f" ... +{len(removed) - 10}" if len(removed) > 10 else ""))
    print(f"\n  {len(moved)} moved, {len(removed)} removed, {added} newly added")
    if moved or removed:
        print("  >>> READ THAT DIFF. A MOVED or REMOVED value is the anchor changing under you.")
        print("  >>> If it is longer than you expected, STOP and work the procedure in this")
        print("  >>> module's docstring. Record in the commit message WHICH values moved, BY HOW")
        print("  >>> MUCH, and WHY that is correct.")
    else:
        print("  >>> No existing value moved. Confirm with: git diff tests/golden/ — the ONLY")
        print("  >>> '-' lines must be the `meta` block. Any other '-' line means a value moved.")

    sha = ""
    try:
        sha = subprocess.run(["git", "-C", os.path.dirname(_HERE), "rev-parse", "HEAD"],
                             capture_output=True, text=True, timeout=30).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass
    doc = {"meta": {"implementation": sys.implementation.name,
                    "version": sys.version.split()[0],
                    "generated": time.strftime("%Y-%m-%d"),
                    "repo_sha": sha,
                    "note": "CPython-generated ANCHOR. Do NOT regenerate under another "
                            "interpreter — see tests/test_numeric_fingerprint.py."},
           "kernels": new}
    os.makedirs(os.path.dirname(GOLDEN_PATH), exist_ok=True)
    with open(GOLDEN_PATH, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=1, sort_keys=True)
        fh.write("\n")
    print(f"  wrote {GOLDEN_PATH} "
          f"({sum(len(v) for v in new.values())} values, {os.path.getsize(GOLDEN_PATH):,} bytes)")


if __name__ == "__main__":
    if "--regenerate" in sys.argv:
        print("REGENERATING the golden fingerprint. This destroys the previous anchor.")
        _regenerate()
    else:
        for fn_name in sorted(n for n in dir() if n.startswith("test_")):
            globals()[fn_name]()
            print("ok:", fn_name)
        print("golden fingerprint: all gates pass")
