"""Emit the expected word vectors for rust/tests/slice_ai_split.rs from py.json, and splice them
into the handwritten test at the `// @@EXPECTED@@` marker. Encoding (mirrored by the Rust test):
float -> IEEE bits; None -> NONE; bool -> 0/1; int -> itself; label -> CODE."""
import json
import struct
import sys

NONE = 0x7FF4DEADBEEF0001
CODE = {"clip": 1, "demand": 2, "fuel": 3, "gov": 4, "tie": 5, "dormant": 6,
        "shared": 7, "air": 8}

d = json.load(open(r"W:\temp\claude\slice-ai-step4\py.json"))
R = {k: v["result"] for k, v in d["readers"].items()}


def f(h):
    if h is None:
        return NONE
    return struct.unpack("<Q", struct.pack("<d", float.fromhex(h)))[0]


def lab(s):
    return NONE if s is None else CODE[s]


def b(x):
    assert isinstance(x, bool)
    return int(x)


def row_words(x):
    return [lab(x["coord"]), f(x["phi_lim"]), f(x["phi_air"]), x["npts"],
            f(x["phi_lim_built"]), f(x["phi_air_built"]), f(x["phi0"]), f(x["b0"]), f(x["v0"]),
            f(x["b0_frac"]), f(x["min_phi"]), f(x["max_Tt4"]), b(x["arrested"]),
            b(x["riding4_valid"]), x["n_cut_fuel"], x["n_cut_gov"], f(x["max_req_fuel"]),
            f(x["max_req_gov"]), x["valve_moved"], x["stator_moved"], x["n_riding4"],
            b(x["b_max_hit"])]


def cell_words(i, c):
    return [i, f(c["s"]), f(c["phi"]), lab(c["authority"]), lab(c["masked"]), f(c["mask_leak"]),
            c["zeros"], f(c["c1"]), f(c["c0"]), f(c["cyc_fwd"]), f(c["cyc_rev"]),
            f(c["pair_RC"]), f(c["pair_CV"])]


def seq(xs, enc):
    return [len(xs)] + [enc(x) for x in xs]


def liveness_agg(r):
    return [b(r["control_ok"]), b(r["levers_woke"]), b(r["fuel_off"]), r["four_live"],
            r["n_split"]]


def arrest_agg(r):
    w = []
    for name in ("shared", "air", "fuel"):
        a = r["arms"][name]
        w += [lab(name)] + seq(a["marched"], f) + seq(a["arrested"], f)
        w += [f(a["last_march"]), f(a["first_arrest"]), b(a["monotone"])]
    w += [f(r["control_bracket"][0]), f(r["control_bracket"][1])] + seq(r["owner"], lab)
    return w


def saturation_agg(r):
    return [f(r["first_sat"]), f(r["last_march"])] + seq(r["cell"], f) + [b(r["impossible"])]


def gains_agg(r):
    w = []
    for a in r["arms"]:
        w += [f(a["phi_air"]), a["n_riding"], a["n_sampled"], a["n_interior"],
              a["skipped"]["switch"], a["skipped"]["regime"], len(a["authority"])]
        for k, v in a["authority"].items():
            w += [lab(k), v]
        w += seq(a["masked"], lab) + [f(a["max_mask_leak"])] + seq(a["zeros"], int)
        w += [f(a["max_cyc"])]
    w += [b(r["vacuous"])] + seq(r["n_interior"], int)
    w += [b(r["all_differenced"]), b(r["ever_two_authorities"]), f(r["control_nonzero"]),
          f(r["max_mask_leak"])]
    return w


def arr2(name, rows, width):
    out = ["const %s: [[u64; %d]; %d] = [" % (name, width, len(rows))]
    for r in rows:
        assert len(r) == width, (name, len(r))
        out.append("    [" + ", ".join("0x%x" % x for x in r) + "],")
    out.append("];")
    return out


def arr1(name, xs):
    lines = ["const %s: [u64; %d] = [" % (name, len(xs))]
    for i in range(0, len(xs), 6):
        lines.append("    " + ", ".join("0x%x" % x for x in xs[i:i + 6]) + ",")
    lines.append("];")
    return lines


out = ["// ---- GENERATED by W:\\temp\\claude\\slice-ai-step4\\gen.py from the Python probe's "
       "py.json -- do not edit by hand", ""]
out += arr2("LIVENESS_ROWS", [row_words(x) for x in R["liveness"]["rows"]], 22) + [""]
arr = [[f(x["wall"])] + row_words(x) for n in ("shared", "air", "fuel")
       for x in R["arrest"]["arms"][n]["rows"]]
out += arr2("ARREST_ROWS", arr, 23) + [""]
out += arr2("SATURATION_ROWS", [row_words(x) for x in R["saturation"]["rows"]], 22) + [""]
for g, nm in (("gains_clip", "GAINS_CLIP_CELLS"), ("gains_demand", "GAINS_DEMAND_CELLS")):
    cells = [cell_words(i, c) for i, a in enumerate(R[g]["arms"]) for c in a["cells"]]
    out += arr2(nm, cells, 13) + [""]
out += arr1("LIVENESS_AGG", liveness_agg(R["liveness"])) + [""]
out += arr1("ARREST_AGG", arrest_agg(R["arrest"])) + [""]
out += arr1("SATURATION_AGG", saturation_agg(R["saturation"])) + [""]
out += arr1("GAINS_CLIP_AGG", gains_agg(R["gains_clip"])) + [""]
out += arr1("GAINS_DEMAND_AGG", gains_agg(R["gains_demand"])) + [""]
out.append("// ---- END GENERATED")
block = "\n".join(out)

src = sys.argv[1]
s = open(src, encoding="utf-8", newline="").read()
assert s.count("// @@EXPECTED@@") == 1
s = s.replace("// @@EXPECTED@@", block)
open(src, "w", encoding="utf-8", newline="").write(s)
print("spliced", len(out), "lines")
